image: mabhi256/sbt-dind-awscli:latest

services:
  - docker:dind

stages:
  - build

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2
  SBT_OPTS: >
    -Dsbt.global.base=sbt-cache/.sbtboot
    -Dsbt.boot.directory=sbt-cache/.boot
    -Dsbt.ivy.home=sbt-cache/.ivy
    -Dsbt.io.jdktimestamps=true

build:
  stage: build
  before_script:
    - apk update && apk add git
    - echo "Fixing git setup for $TRAVIS_BRANCH"
    - git checkout master
    - git config --global user.name "RAJAT JAIN"
    - git config --global user.email "rj.jain1008@gmail.com"
    - git branch -u origin/master
    - git config branch.master.remote origin
    - git config branch.master.merge refs/heads/master
  script:
    - $(echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin "$CI_REGISTRY")
    - sbt releaseMajor
  dependencies: []
  only:
    - master
