image: mabhi256/sbt-dind-awscli:latest

services:
  - docker:dind

stages:
  - build

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2
  SBT_OPTS: >
    -Dsbt.global.base=sbt-cache/.sbtboot
    -Dsbt.boot.directory=sbt-cache/.boot
    -Dsbt.ivy.home=sbt-cache/.ivy
    -Dsbt.io.jdktimestamps=true

build:
  stage: build
  before_script:
    - apk update && apk add git
    - echo "Fixing git setup for master"
    - git checkout master
    - git config --global user.name "RAJAT JAIN"
    - git config --global user.email "rj.jain1008@gmail.com"
    - git remote set-url origin https://$GIT_CI_USER:$GIT_CI_PASS@gitlab.com/$CI_PROJECT_PATH.git
    #SSH setup
    - apk add --update openssh
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$SSH_PRIVATE_KEY" | base64 -d)
    - mkdir -p ~/.ssh
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
    - docker login -u $REGISTRY_USER -p $REGISTRY_PASSWORD $REGISTRY
  script:
    - sbt releaseMajor
  dependencies: []
  only:
    - master
